app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/onedr0p/jellyfin
            tag: 10.8.11@sha256:926e2a9f6677a0c7b12feba29f36c954154869318d6a52df72f72ff9c74cf494
          env:
            TZ: Europe/Vienna
            JELLYFIN_CACHE_DIR: /config/cache
            DOTNET_SYSTEM_IO_DISABLEFILELOCKING: "true"
          probes:
            liveness: &probes
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /health
                  port: &port 8096
                initialDelaySeconds: 0
                periodSeconds: 10
                timeoutSeconds: 1
                failureThreshold: 3
            readiness: *probes
            startup:
              enabled: false
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 1Gi
      pod:
        securityContext:
          runAsUser: 568
          runAsGroup: 568
          runAsNonRoot: true
          fsGroup: 568
          fsGroupChangePolicy: OnRootMismatch
          supplementalGroups:
            - 44  # video
            - 109  # render
            - 65539 # docker
  service:
    main:
      type: LoadBalancer
      externalIPs:
        - 192.168.20.140 # TODO: use cluster variable
      externalTrafficPolicy: Local
      ports:
        http:
          port: *port
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        hajimari.io/icon: simple-icons:jellyfin
      hosts:
        - host: &host jellyfin.ismailbay.dev
          paths:
            - path: /
              service:
                name: main
                port: http
      tls:
        - hosts:
            - *host
          secretName: jellyfin-tls
  persistence:
    config:
      enabled: true
      storageClass: longhorn
      existingClaim: jellyfin-config
      retain: true
      advancedMounts:
        main:
          main:
            - path: /config
    media:
      enabled: true
      type: nfs
      server: 192.168.20.50
      path: /mnt/tank/media
      globalMounts:
        - path: /media
    transcode:
      enabled: true
      type: emptyDir
