---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBepCuEeqTTLgawAxvTpgqFQxQMFD9l9sALZ/wLOHr8ATeNoCCu6tjFNe5cOmXcE23xKXBFI0MOHYhoqmNzzRPseC3a1Y7Yf2WnUr3tBmw97p/584rINgKEChFAp6UTzL2X51wze/8o3Mj0FBVXqYMYlVRVpAF2XElK9EPjIaL8+HziM4yMRRCnapldnyNXPRoySEu+YHi11owQHl1eDbhQ6ngZyg6vEAf4qOfA/BiASwisDhuJBFlNpvjIsQ4JgphanYorY7wD2DgY3dCbKL/ecTO9N+pvoQfc7+iVP07PX663hDI9FnTliaDhAK0HC3e/EyBEt+dzCOCyhT0Ij17nneyTIlZiLm/gsrYSdbaGUSKMMsA7wFILmNQM1v5RmjaNJlIzuKc8PppkNDwcvfZY0EQHgU8UIltqHBIKgQqtGFVPbNNE2qZGOtFMqSju/6cUeyS+vLC2SVaZSV/LUvR3DPaKFozaGu0Jo0WSH01kKvrj4ear93t7/JGLBTxJFDSzzV3867hwlwu3JnKc/ZrbKDImnu/ft9OQ3h/V48hMbGoNNGFaxch4lpVEmKbf3UQvB9iJuwSRHVtZunp8WqzMEQ0qNlzcgfTkkVavSm0A4wJNdhfylUUz4xVQ5IAiH4sgQNHHsENRQlphOMcFdVJZ613xrXXt7tvuqWGWv4XEJ0COXKWHYXCgziyOX2ObH2R32uVyT9aANoeKgBDzzGAMQfVixA==
    admin-user: AgBYybnriGWTskRZdmgYwllEUwN9cgfZvBsuc7szWroK93IgS/GRai+b8E/mKsDj891rniaw1sPNfMLk8qKyj1LsR0QvhNX1zJY/57tpjPhzLytsgAhM+DRmWSEjVpbc0kRAkjKmTfJuFxB827CnZZcCHg5MEBU+59kDw7jYDVMJxSkzRGLC2FEDfEFBnZBHj2avD4BaSXUMphwf5c/EJE64S1GwLgHmiv81vhQz8r+xoZ6O2muswIleUE7HKtm69rGjV9zXSl5Bp7pmXJcUJNfmuEGKRflCGOeEglVK+ZKfM5FwjTDErO0S5B4+/tZsgutesTje2RhDWexvhR43I0rmOoEzLloqr85HndvY94EbTsoN7nWtLcwYZtt0tqW4qSK1868BqqtFLcoWzaUyhv1wmKBDExhJ71JLnzNDqrKJgZcloPKWH5pagHYx0CDJn66lniQeWzUwmgrb5wwTZ6E85cQF80NLSir2p1DfAKB1ZWhlk3mQBZVyDDu9FyalPv1AGQI4GDgOMdigRrTTkywoHCKWyrCI+YfEdL3lvy6pwGB0iHYx8xp2SOZ1OdKSZtR1nAp0ZRGT0m5L2nePwwTEqAoriePwj0HVjye8z9CHk4qACUbR8bOjSaGO1qcRKq+pWcxtxOpr9uSzm14xSwcM6zOk1GUd2GlEzGs1hxtVgL/2KPcnextj8LGtoGtM4ZlQekNrEQ==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-secret
      namespace: monitoring
