---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBG6j042Niak5/OD8IxaYhM5BbqwU5CTzbMdNcusuSov1e0whhn4mMtaN3PPNy4JZjQbivFwaGztB/W1WXk9Hd2rwvHH7UOlX69z8f3RNHalAHYrQjr22qfV1FRifKgw7HilsbwvEyl0NFxzuvEKZ2H+PEGbmBXteHRQzoHOKHeZUW5za8gCHljLxrwuSZQkQUvfKDia4q/hGGLpM3sfY+Df7XDEvfcX9bOpl39ZwmcM06BzSTujJo/k0iG5Bw0ICLUWAwXF3LUea2rim7gMEs1av3ljUYicfZjVXZDAzmDsWbD4WOxPXaBIWNeWfH6DmuTZZ++H7C6CRLy5mh2Nguh5oHAUbvqj+tV369Cspjfq8vRQygkkGaEDk6ZVR4528Po6bf9ynahSafL+FFPfGCBmzQydfwuUdeoc6/i04TSNhBrgKI/9B5oBw4LoCc9z15PFhw3cvJhg6BiAlQwZDvBGYPIVwFYEnh/ozZaxKbaxkhdeA7afGPxVw1HC0Zk4l1yQWREiaZuOo5q+m0tt4JT2S6JJhDkS2xmbDVR/OH/MC1QtOnbJ6Du5PqmHVQiNZudDqOniHpu9c7LrAoAnn77HsbOoGFttYz6Yz50fhxf3flYzyQD0MvF7DKS7YrqJNqsxoZjQlUepXGdAEb0Yak7TNG+1Gc48fegzL52YCB4h+7j8tXXSPJrEN+i3arK7isfz090sqTgoge0G9JJNyDVQRIbxA==
    admin-user: AgCOL5sjlxDKAY+0VOzEd2Wb+LUnqYRx32aHh5cdgQkzZp+2tG67roUSqj1JCcpZaQP9DTDWuAkBfjPAj7ner9K5DOGvFKApNPrYV2ooB0Mb5D3G1ZL8OKNtTkYb37Vh7E0CiMy3lCXI3334AssXccgM4YyJFOjirDdHDo+KIZtNBmwfol7DnVJbCq2tbsYTUl9g5w1SCpCMchGB496gw3pm7Vma/cY5cuRE4d3nIyLTW57HFslSxSbg6C4w9ZkSLyIHYQfOvh5+TLXcZg1vztONiXH5iUDL8B2EenuAR9Y83T6knrS/vvpAzoVp3d7IWJnOcoaCZw6QlQggxq087OP2NL+c6H48YlUMQjH2XqV4kYP4XwUow1BVV4jJDMtlQU7sydAd6iwfnjYEFn5ceh8ZLplobWJNerhq6fR0CG8dhugu9bUgdsK70SV7LKZ0WPMNqCIeCaUSLB6kCUWUHrubYOA0xnWxX9nLe8ggA0X/Mn3SKXReoMKec4F+LltnUQ0Ky/0i7jDkA6YbzTIk/u7eLYZ08UkiyAaZxj+PEGzxFoiQuEVPzRZzFVsfj9YX1YlYkYORrOFOf+viNCBj73pbZXocmGxS68Qg+8mBkzrRAYdjLwNn2K1dGZRSviXkwn6TUSNydLo/iWxzYBpTD7ddDTZHwlCCTekyH8xtqlcVHkSBDiUBGLjXFUb3gsYIDRLraJVGuw==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-secret
      namespace: monitoring
