---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCxp6/3aWW6sam94NCpt/X8hdO0c+Fl2BLbfh6KKGMll+jzPO8XepBV97ObLsk5PEABRrDnqQonaR6pL7E0mjygn/jfBWjGIyiiPvgBCz6NnrTKeCklRH0Ohwc3PIUwvFyC6VKT/slUmkQQ9Om+QktCyYm3dkHd9UKpQ7na5op8eXTCBtP1RGjA3FxwhLKaGvZl2CUpwSdscT67mILkm+PAtkJN6ox7NPZrXxpr83arbBPaQB6LCLmdoUX9k/gn8nr22d76ZxDhX6M4e1+SXZFTFAH6rN8gl9INlQ9M6OtUJegtSyMnASEFkmFH3pPrgJZ4zopp8XZSvrc6eOadzzncFlW5BNoAEe0V7HVuJX8758zqenH9uegt6gy2o9XAHpyyqldu+amDxsDqSAOxx+eaZu0VMgJH12YmawTS8VVB2PFhpxB0OmuG37feOiiWuVzOdJZpOhWjmpXY2fe/wBFrJ1jjLPxFuNzkkYbwwdCAoocUp1jPU61IRypeyrfIesbvPwOHgAsOwKKZy3g228g2G4BoBjdjteL6deKwbQPpXH29c7CBe3+nkoAuxPE62+lAN5Iy45q5sl2DR5Ew0f2uooXCPvg6repMQLTeoBTXhFolbG7+0FhuJqtXl1gy3lkd03xMEh0AUkbT9cuhasCnjczKuRDgwcVtCfxghLOVkcIZWSEh/f9GRG6p0u6N7xErhoaAVfk32sUKQU6ZzV4/VvLFOw==
    admin-user: AgAG2YDSQYQVR2nezdt+UFHzf8KaPbrA+txNt/HgH9/5fNFPLXdY4+K7g6/hSKjmdEB5j3GVbWuYaPl42c9kPIcbac/yOnSj/97GVeJVKXDf8jASLu3aF0RdNF83/hveJguUtbAhO4gocWAZZFlEFZRPBN/fX/vy5q4yqMoo29T2dyVfx7MxN55lR8RyzZsGyYe7cYjEY5NE4dreCM88CNw96qqmGtsI0XySU1U9+prKDnKr9uKSgC4VATbF5wx7noWmOhp5U6gJ9WGRHBxiKQ1kcSvmYv/4cwZumKg4aXvpbN8gS3c5+GTrUmWEE1RfUe1sFcxK4VupZqmSE7quD+zUwESrj+FnS/OC8F6GgW1NV4gsgLVjjFs52wei35/CEIXAG38vb6kRyuvP27s0YW44YWDP9Sdxd4A3PTpmdBhtjUlPzE0Nij/JS6pPcwLcXIy21fW6nREy737iqlHQtY14xFUH+sPNd+EPOMdac3p4/p8f2+uNEG+0ERboo3kkYg/T9mT5V9JiNO/cV2yex7r4rOcsJ5gMswF3ayUlsP+nH8sm9F2+A29qNfXLe+D4LdbMGEIQeglmy8l01mZXO3CZ1T9AjciIbdICTG2JUjS7A37C6PW6QwqphKoSa3atK4TdNLEInHriY9Wasz9Gv1WY7Txx95P2IGhsC7v0uQMVnvrDuYPd4FG95x0WTTZyN4yJctdyrg==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-secret
      namespace: monitoring
