---
version: "3"

vars:
  ANSIBLE_DIR: "{{.ROOT_DIR}}/ansible"
  KUBERNETES_DIR: "{{.ROOT_DIR}}/kubernetes"
  TERRAFORM_DIR: "{{.ROOT_DIR}}/terraform"

env:
  KUBECONFIG: "{{.ROOT_DIR}}/kubeconfig"
  SOPS_AGE_KEY_FILE: ~/.config/sops/age/keys.txt
  
includes:
  ansible: .taskfiles/AnsibleTasks.yaml
  cluster: .taskfiles/ClusterTasks.yaml
  
tasks:

  default:
    cmds:
      - task -l
