apiVersion: v1
kind: Secret
metadata:
    name: jellyseerr-secret
stringData:
    API_KEY: ENC[AES256_GCM,data:B7tKNIslDtSroOkaoDRm8NhlGd9qUGUUqHwJyJrohfTjOvZCOJLgVpbykuMmYP4ETV0+Aol4lBxXa9n/A2tRqZdTOwk=,iv:hQwMcan0GY1j/FJr/NaXnsuJ4VFywBiEv8kbOyG7MmM=,tag:pi0dY21H5HMUGBQFjVLeXQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rpz38k8uhgr5esalc2fr2jmced6m2c4j0puvs07wqm2u9ssg79ds3hlcam
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwMUR6cTkyVTFDMWVwTVpw
            TldoRnEzWkJnbkIreGlWd0lRcUM4aWFIalVvCitzQy81aCtlZnYzZzJtVmpxZjdF
            VnQzMnhSVEQxWkorTDltSGl0Z3NhTWMKLS0tIGpGYmptb3MwUDdGSDFsK1JnbU5M
            Sm1hT0ZnNE1qUWZISnJ0NDVxUE0yalkK70LHRRVwNtjPKopKVQfXCSqiFMfYorXV
            p/fIaksYE8pwgGA7jM0Z4C1XzdMKYHcevVp8C2I90h7yhHNEBM0LHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-01T10:46:27Z"
    mac: ENC[AES256_GCM,data:Oigvhm+FoNs38tW5ipxtHmtwln3Sz98PhV3phRh/cGPsUwZh8D49NnORbVXEMKJKkb6z5Zx5yT6e2OT9CqFzq8wdYWW0mfPQHC6qjcGRo6o+b5KoAH1VV5NlMno+gwAC1wDlJKrbCJ/l/E74lnEOFUul5BjH0SbbV5JAkFJd3CE=,iv:1O+3UWIKrbH5fjWLaDGvJIk+L7WlWbz3SqKHGjdhkBU=,tag:lp6PF3WVoczsQQlsIhsM5Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
