app-template:
  controllers:
    main:
      type: statefulset
      containers:
        main:
          image:
            repository: ghcr.io/onedr0p/sabnzbd
            tag: 4.1.0@sha256:1c1650511f96108e81d677abe8a2e491507caa023fdc5c2bfc99df087634c9f3
          env:
            TZ: Europe/Vienna
            SABNZBD__PORT: &port 80
            SABNZBD__HOST_WHITELIST_ENTRIES: >-
              sabnzbd,
              sabnzbd.default,
              sabnzbd.default.svc,
              sabnzbd.default.svc.cluster,
              sabnzbd.default.svc.cluster.local,
              sabnzbd.ismailbay.dev
          envFrom:
            - secretRef:
                name: sabnzbd-secret
          probes:
            liveness: &probes
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /api?mode=version
                  port: *port
                initialDelaySeconds: 0
                periodSeconds: 10
                timeoutSeconds: 1
                failureThreshold: 3
            readiness: *probes
            startup:
              enabled: false
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 1Gi
      pod:
        securityContext:
          runAsUser: 568
          runAsGroup: 568
          runAsNonRoot: true
          fsGroup: 568
          fsGroupChangePolicy: OnRootMismatch
          supplementalGroups: [10000]
      statefulset:
        volumeClaimTemplates:
          - name: config
            accessMode: ReadWriteOnce
            size: 1Gi
            storageClass: longhorn
            globalMounts:
              - path: /config
  service:
    main:
      ports:
        http:
          port: *port
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        hajimari.io/enable: "true"
        hajimari.io/icon: mdi:cloud-download
      hosts:
        - host: &host sabnzbd.ismailbay.dev
          paths:
            - path: /
              service:
                name: main
                port: http
      tls:
        - hosts:
            - *host
          secretName: sabnzbd-tls
  persistence:
    media:
      type: nfs
      server: 192.168.20.50
      path: /mnt/tank/media
      globalMounts:
        - path: /mnt/media
    incomplete:
      type: nfs
      server: 192.168.20.50
      path: /mnt/tank/garbage
      globalMounts:
        - path: /mnt/downloads
