---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cloudtooling
  namespace: flux-system
spec:
  type: oci
  interval: 12h
  url: oci://ghcr.io/cloudtooling/helm-charts
