apiVersion: v1
kind: Secret
metadata:
    name: sabnzbd-secret
stringData:
    SABNZBD__API_KEY: ENC[AES256_GCM,data:YpqRz6TmgjjUxHzS6YV1Ia6UJxIZjHa/Wzeyy/ZZdm8=,iv:DUWz+k7W9+mLTLxLhZX+BtT3ejqLt5AhsrMvYSFgcoc=,tag:PPTnKnrJYgVCGXvA4p04Iw==,type:str]
    SABNZBD__NZB_KEY: ENC[AES256_GCM,data:ZZYejAs29BQkAcFAbLP9Z+Po5fKeLpnxeHjGcVocs4s=,iv:+iI+wJ5wbjVgiGHqBjLd44JvKKuOR7fhh8dR2Q6PQV4=,tag:Zxx+4B5VcPVL1sAY/a5XRQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rpz38k8uhgr5esalc2fr2jmced6m2c4j0puvs07wqm2u9ssg79ds3hlcam
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFOTIyNU5UTzF3NXN4dWdE
            QTF0S3NabGVqYTQ0bHdPOFBPZldaa3prVHdNCjRsZFpyUW9JRi9hMzFMT1IvbjR5
            NCtjYys2cWFPRnd1SmtLdUdVYmpRbjgKLS0tIEtpd3VSYWhQQnlkd2NKbVJOdyt4
            bmpJS2lJRUZqVzJDUUg5RzYzdnN4TFEK6rCbmqrnfBYVbCtf7PIUVhhtRAFdCHHc
            IKTVjUK1UBtVUpsOCLDiU3I6rx0EZ2iJ0zImIQKE33L2EAEM+aae2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-16T13:54:41Z"
    mac: ENC[AES256_GCM,data:M4qgZX7ZTVsBMyUXDaYZlhjxZPZMY5YA8Tx/ROcLggPmyBI4EtlPxXtnPW3ZFKzpLyD8LicYhASaOOdC7TCac3Pz5XZW+PsagAqMb1/V7kIBTF9ZJ0e8l16KBe/65WIqeRm+beHE6fZM8Q/RQWe42llO+574PBatFfMuV7Cf5N8=,iv:2rcCdbSwDy0EyRs9gduZMYjppu1B3xp8gU0DENtCsxc=,tag:GJDeA2Ykqh2n4e6eBTE0QQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
