{
 "title": "S.M.A.R.T Dashboard",
 "description": "Dashboard for viewing detailed disk information based on S.M.A.R.T data",
 "tags": [
  "prometheus",
  "node_exporter",
  "smartmon",
  "SPN"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(smartctl_device, instance) "
    }
   },
   {
    "name": "disk",
    "query": {
     "query": "label_values(smartctl_device, device)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "【 General 】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Disk Drives Monitored",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(smartctl_device)" }
   ]
  },
  {
   "title": "Disk Drives List",
   "type": "table",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "label_replace(smartctl_device{instance=~\"$instance\", device=~\"$disk\"}, \"instance\", \"$1\", \"instance\", \"([^:]+).*\")"
    }
   ]
  },
  {
   "title": "【 Temperature 】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Temperature History",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "avg(smartctl_device_temperature{instance=~\"$instance\", device=~\"$disk\" }) by (instance, device, model_name, serial_number)",
     "legendFormat": "{{name}} 【{{instance}} {{device}}】"
    }
   ]
  },
  {
   "title": "Temperature Bar",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "smartctl_device_temperature{instance=~\"$instance\", device=~\"$disk\"}",
     "legendFormat": "{{name}} 【{{instance}} {{device}}】"
    }
   ]
  },
  {
   "title": "【 Wear and Tear 】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Power On Hours",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "smartctl_device_power_on_seconds{device=~\"$disk\", instance=~\"$instance\"}/60/60",
     "legendFormat": "{{name}} 【{{instance}} {{device}}】"
    }
   ]
  },
  {
   "title": "Power Cycle Count",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "smartctl_device_power_cycle_count{ instance=~\"$instance\", device=~\"$disk\"}",
     "legendFormat": "{{name}} 【{{instance}} {{device}}】"
    }
   ]
  },
  {
   "title": "【 Errors 】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Raw Read Error",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "smartctl_device_media_errors{instance=~\"$instance\", device=~\"$disk\"}",
     "legendFormat": "{{name}} 【{{instance}} {{device}}】"
    }
   ]
  },
  {
   "title": "Error Log Entries",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "smartctl_device_num_err_log_entries{instance=~\"$instance\", device=~\"$disk\"}",
     "legendFormat": "{{name}} 【{{instance}} {{device}}】"
    }
   ]
  }
 ]
}