apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:hYHrZB6YP6kduNy0YSyiovsVdrE0S++W,iv:WIJsjwCXypaBqxJbwcqFnV3FOGyZwa7eL90ixdaTw0c=,tag:s3r+WYR4f08+0EKotSwnDg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rpz38k8uhgr5esalc2fr2jmced6m2c4j0puvs07wqm2u9ssg79ds3hlcam
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrZ0dMSzFUWEQrSUt3V1B3
            alNoUjlETVB4TjJENkp4Y2pBa2x4Q1d5amdZCmhYT2xhNmNrZjdxb2orNDVGWU1H
            MEpBMFBDWS9WSDdRaXE0SnQvc0c2YXcKLS0tIEdyOFNzQzdvbE03NGVaQWtDb2dk
            UHZYdWNqVXRkdW1HMjNiZWJjZEFCZzgKdm6zgpDuBcIdpOPcgWXa53RPbxDm+Bvx
            IHwCU86E4jMf8HbUjd88En5A3rNEuXWDsnfBAYu6ysMNcQugp4ai8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-23T18:59:38Z"
    mac: ENC[AES256_GCM,data:RV/8+35VWzZekz1qw9DvBaOp8GUpKTlIl9q88e6vFzpkx3rvmJmLAeXes5uU14qefMkC4wRCKYOp1sKCAE4TPsMEQDtgnVK20Sg9dEfGu00ehYDRL1W/FK90WMP5q80Hj1EDoVuigovPHa6Yh0b3lUc7OfCQC1s59Z0Dr00l9lg=,iv:5Hira3CVfN+GqvT9LowCdOSJcwUXYytnrNoVDx6APgY=,tag:AEddQGcf4bo2mmVUX7fDJw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
