---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: kafka
  labels:
    strimzi.io/cluster: kafka-at-home
spec:
  replicas: 3
  roles:
    - broker
    - controller
  storage:
    type: persistent-claim
    class: openebs-hostpath
    size: 20Gi
---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-at-home
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: 3.8.0
    metadataVersion: 3.8-IV0
    rack:
      topologyKey: topology.kubernetes.io/zone
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        port: 9094
        type: ingress
        tls: true
        authentication:
          type: tls
        configuration:
          class: internal # nginx-internal
          bootstrap:
            host: kafka-bootstrap.ibay.dev
          hostTemplate: kafka-{nodeId}.ibay.dev
          brokerCertChainAndKey:
            # reflector annotions on nginx certificate
            secretName: "ibay-dev-production-tls"
            certificate: tls.crt
            key: tls.key
    config:
      replica.selector.class: org.apache.kafka.common.replica.RackAwareReplicaSelector
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
  entityOperator:
    topicOperator: {}
    userOperator: {}
