---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: rackaware-test-topic
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-at-home
spec:
  partitions: 3
  replicas: 3
  config:
    min.insync.replicas: 2
    retention.ms: 86400000 # 24 hours
