---
kubernetes:
  children:
    master:
      hosts:
        k8s-1:
          ansible_user: root
          ansible_host: 192.168.20.110
          data_device: /dev/nvme0n1
        k8s-2:
          ansible_user: root
          ansible_host: 192.168.20.111
          data_device: /dev/nvme0n1
        k8s-3:
          ansible_user: root
          ansible_host: 192.168.20.112
          data_device: /dev/nvme0n1
