---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "ismailbay-dev-production"
spec:
  secretName: "ismailbay-dev-production-tls"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: "ismailbay.dev"
  dnsNames:
    - "ismailbay.dev"
    - "*.ismailbay.dev"
