apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
stringData:
    admin-user: ENC[AES256_GCM,data:zvkQWjs=,iv:pacCigJRtCYH49Hy6EDxlRzZ5DHLJY5v49tLry7sREQ=,tag:rQsYqbCsK+7ZGCHdzSgfLQ==,type:str]
    admin-password: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rpz38k8uhgr5esalc2fr2jmced6m2c4j0puvs07wqm2u9ssg79ds3hlcam
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFWStpOXRFWVJ6Z0t6YkNr
            ZklpTTVaYUhOWE9qQXJMVW45b01LWTZ3TUZ3CmtBSmdCRFk0UE90OGg2eTBpMHhP
            c2VPeWtYUUY1WGx5UHFIbS90amozQk0KLS0tIEVNK1hXWCszUDdaMEtDK0xUekEy
            VkFqdk5BWko2aWNxd2NqajNJaGJFUTAKZK0l5GsmjwQ86Rp3z8mouktgNTGwNCYe
            DXQgBrDd9sqqnfZ3+g8WNERRDfbaDvm+bpBydw8PHd2PXQjPIX8C0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-23T18:59:38Z"
    mac: ENC[AES256_GCM,data:8GJ8tAwRAZNlP1bMs5+h4W00v27FDl6lae11tYxgVVROT5b/QscJytweYfRiJxnePfu4I714ac/8tOhvrHVdi+cFRs65SviDcQFqYZFYLrdQrk3eg4JOND7YQdB/ZFKp4fWP1No6482N1iUxfgXbCJ3t8gGumTCdO+liHOYUnjk=,iv:/xRccLObkrM1oZ01J9jtMHpaoJCQCRYMTHVXfKC0+wo=,tag:UVME9kYuh7I28LT3jW2k2Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
