---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: radarr-secret
  namespace: media
spec:
  encryptedData:
    RADARR__API_KEY: AgChdRFlRKIAa4pn3gM3sc82UdxSxNzPe1+cvt7nPO3udpQmH2WX1vaTD6OVnjRC3zk/hUlIWOY0WE6tQxwU10BhgsOdcmN89f7R9jqmwguITzgYy8Ga8g0qFF/GLfZMA9SgzDgzPdbXT3J8dB4MswkcQEc5279sU9lNLUYiMff51mPOnioT4McFKN+Y07oYhGr8equXAagDzK7Q3kj8FQqMwQFUSFQzIIa+zfxYFye6eQEAPyaN7hy76BJnWrcHz4JpRHzhVfxef1RqwNaZsXuNHs8plbFxXZU1yOha8CRy4DLDV7EhZb7yL+zTMy4bik2o1qaR/deEcXWXgRiLmrL6TgCrq7q77q7LuEAXIV6Lr44Z3ArsG6yHh9rrubT5epj5fZPKdwfRf1dTlNcosp0cjJH5GNtTO2ySDqtbb5HJ7OVrRV+Vh9/zpHFvawa1rZN1YSm3U3tclzc6PvprT6d/jjwcfSHR3E/LqVrGCJgDDsaQR2Ks6rsHaTUTmMZfmkqqjFP37SHQ/vzbckO1wufixAnQf6CesKHGS19b6JEQe0JdEz6ClhL63uF+XsS+usiZZ+BhQ1wDqDfxvqTSynKHg5sn9epdwuBhGMgZ+OPNe09skxvIl5Krw2+td/qDB+0kcvwsD6E/Jyaru0JQqvBaHinkM/QeqVt5B0iCNv1cLvmygWSM2+u1LJ6b+CJKL0Wjoio45sUa+T4o2Y2xlahFkDXSx9IlALlVl0DX1s7jcg==
  template:
    metadata:
      creationTimestamp: null
      name: radarr-secret
      namespace: media
    type: Opaque
