apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: rook-ceph
    repo: https://charts.rook.io/release
    version: "1.12.9"
    releaseName: rook-ceph
    namespace: rook-ceph
