---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: prowlarr-secret
  namespace: media
spec:
  encryptedData:
    PROWLARR__API_KEY: AgB7f53hsIXYFsOJLJ18Ohs+9J1IpDOKCo4n/iqO5Y9Z4B+VSABOHQopsaWkfVM2Pj61Tls8TrrRmyqJWtjk55HBaEbABKokJmsZypp9fxTZo5ab7p1dZ1U/kIacLQ5osHp9qJffE7ta/+66JgmsO9HBACVdJ6NcEZbc/u2WHDu2crgJEQkHNyqJ6+MR1/TwDqnTwPJ5HxdOYnL8Fmk3dwlznWQpdgmoy+I/bkqlZfP3jnI6We1KyDwngfBCM+qADm5zNpv0CbjtaZat7s3dQqa2P9KO4AqefIqFyZm7kd/WJwQ4Q8yWCZQtFMVlBOwgv/PHRbeso97Uaidw57Yd3XkknsY7cn1FftmfeTd7xen7dkkZPRZa0TA89zjFO0vDP+aUW99XXKzlNMrtqMk96n+qTpOfZy5e8hjsiEAoHu9rm53rCWKKJNwCtDv3R+k4mucKL4Fx738r+NyZWcj8JPAocJ++sfR3arETcQyCd0381AvXVYZMbLQbvlzOR+aexiDON5xBdbIBbfgHkcYnFcmvFyCGoxwKlhN45vcvr+ZoTM3lOWwpjATA5WDo+5NXe+U3Ez8FVTV8M3AIMQc08fHXelK8UBqaY3dy8Gjc2dbJ7ZRPtvsbWoMMp6Dz5FNBQ5HmjrP3IQqlLnec7eZc9gSHEGFaWAulYWQiDv0NdzjAzKJ9EZSi8oPbCX/NmAjbNQmKQ25p/9nw+oFe0n1yDV5JFmSUVL40++X18ZaIpUp7bg==
  template:
    metadata:
      creationTimestamp: null
      name: prowlarr-secret
      namespace: media
    type: Opaque
