---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: mongodb
  namespace: database
spec:
  chart:
    spec:
      chart: mongodb
      version: 14.8.2
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 10m0s
  values:
    image:
      repository: bitnami/mongodb
      tag: '7.0'
      pullPolicy: IfNotPresent
    strategy:
      type: Recreate
    architecture: standalone
    useStatefulSet: true
    clusterDomain: "${SECRET_DOMAIN}"
    auth:
      rootPassword: "${SECRET_MONGO_INITDB_ROOT_PASSWORD}"
    persistence:
      enabled: true
      existingClaim: pvc-mongodb
    service:
      annotations:
        io.cilium/lb-ipam-ips: "192.168.20.135"
      externalTrafficPolicy: Cluster
      type: LoadBalancer
    externalAccess:
      enabled: true
      service:
        type: LoadBalancer
    diagnosticMode:
      enabled: false
    backup:
      enabled: false
    metrics:
      enabled: false
    resources:
      requests:
        memory: 100Mi
        cpu: 10m
      limits:
        memory: 400Mi
        cpu: 900m
