apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:U1zENl2MeGu6dznbLbP0RIbtCRaFIfZBz7kRDcy1J1rn99G3Kxj95A==,iv:Y1PwEVyZYwTjJUfkV7wcQ67B1NPSStHRd2+dHAZ53IQ=,tag:bsDq0dhv+AH8gXCVz8qqaA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rpz38k8uhgr5esalc2fr2jmced6m2c4j0puvs07wqm2u9ssg79ds3hlcam
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMaXhJUmFtZ1FLY2VqL0xo
            dUFldzFsSERjTEFySzI5ZU5EWHh5UjNSbVFjClhpSjd2L0VJdFhYQUJ2dTlZNVM5
            K2pxcnR4YTFhSU43RmdGNnlrZjVaQ0UKLS0tIE9heHN6a2R2eHppQTQxUk9OdUhy
            OGhweG1JT1lsVlR0WSthTHNOdnB6Sm8Kx4/8YMZudJpf53gyzo3IdffT2IJiY6KQ
            o0hheMTUk/T9Y5ttVb7nSW4Ep64mDAUqeJKBQ6e8ayVKXKKrXF/kdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-23T18:59:38Z"
    mac: ENC[AES256_GCM,data:4Szx7FjnVkU7SW4c4WjWP7EQMQsau85nUVZWNzWqwUg+iBEr6TFphlJjl4ArIhkeGVhetdYR3XoQHBD5a4/XjbLisH7PSZ66gpVw8gmAtHXEDKdwRELIigH8fsYrigOQrzjz2r+Cw9OdhidbcQMw89mOwU4At1BSxswrWH9MUqs=,iv:xH4uUd511M6PO2sSkdfOYwHZii07kuKtYJL+5ny6txw=,tag:CWn+O3jC+kDcj50B1eCsQw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
