---
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: home-assistant
spec:
  postgresVersion: 16
  instances:
    - name: postgres
      replicas: 1
      dataVolumeClaimSpec:
        storageClassName: longhorn
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
  users:
    - name: home-assistant-pguser
      databases:
        - home-assistant
      options: "SUPERUSER"
      password:
        type: AlphaNumeric
  patroni:
    dynamicConfiguration:
      synchronous_mode: true
      postgresql:
        synchronous_commit: "on"
        pg_hba:
          - hostnossl all all 10.43.0.0/16 md5
          - hostssl all all all md5
  # dataSource:
  #   pgbackrest:
  #     stanza: db
  #     configuration:
  #       - secret:
  #           name: pgo-s3-creds
  #     global:
  #       repo1-path: "/home-assistant/repo1"
  #       repo1-s3-uri-style: path
  #     repo:
  #       name: repo1
  #       s3:
  #         bucket: "crunchy-postgres"
  #         endpoint: "192.168.20.50"
  #         region: "eu-west-2"
  backups:
    pgbackrest:
      configuration:
        - secret:
            name: pgo-s3-creds
      global:
        archive-push-queue-max: 4GiB
        repo1-retention-full: "7"
        repo1-retention-full-type: time
        repo1-path: "/home-assistant/repo1"
        repo1-s3-uri-style: path
      manual:
        repoName: repo1
        options:
          - --type=full
      repos:
        - name: repo1
          schedules:
            full: "0 1 * * 0"
            differential: "0 1 * * 1-6"
          s3:
            bucket: "crunchy-postgres"
            endpoint: "192.168.20.50"
            region: "eu-west-2"
