loki:
  loki:
    auth_enabled: false
    commonConfig:
      replication_factor: 1
    storage:
      type: 'filesystem'
  singleBinary:
    replicas: 1 # TODO: migrate to S3 storage
  write:
    persistence:
      size: 10Gi
      storageClass: longhorn
  read:
    persistence:
      size: 10Gi
      storageClass: longhorn
  monitoring:
    selfMonitoring:
      podLogs:
        # https://github.com/grafana/loki/issues/10757
        apiVersion: monitoring.grafana.com/v1alpha2
