loki:
  loki:
    auth_enabled: false
    commonConfig:
      replication_factor: 1
    storage:
      type: 'filesystem'
  singleBinary:
    replicas: 1 # TODO: migrate to S3 storage
  write:
    persistence:
      size: 10Gi
      storageClass: longhorn
  read:
    persistence:
      size: 10Gi
      storageClass: longhorn
