---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: mqtt-on-truenas
  namespace: monitoring
spec:
  staticConfigs:
    - targets: ["mqtt-exporter:3321"]
  metricsPath: /
