app-template:
  controllers:
    main:
      type: cronjob
      cronjob:
        schedule: "@daily"
      containers:
        main:
          image:
            repository: ghcr.io/onedr0p/radarr-develop
            tag: 4.7.5.7809@sha256:f2044d2e8bd2e8d24e8a79f051404be80400f450a94b4c481cbc93cfeffbe745
          env:
            TZ: Europe/Vienna
            COMPlus_EnableDiagnostics: "0"
          envFrom:
            - secretRef:
                name: radarr-secret
            - secretRef:
                name: sonarr-secret
          args: ["sync"]
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              memory: 128Mi
      pod:
        securityContext:
          runAsUser: 568
          runAsGroup: 568
          runAsNonRoot: true
          fsGroup: 568
          fsGroupChangePolicy: OnRootMismatch
          supplementalGroups: [10000]
  service:
    main:
      enabled: false
  persistence:
    config:
      enabled: true
      storageClass: longhorn
      existingClaim: recyclarr-config
      retain: true
      advancedMounts:
        main:
          main:
            - path: /config
    config-file:
      type: configMap
      name: recyclarr-config
      globalMounts:
        - path: /config/recyclarr.yml
          subPath: recyclarr.yml
          readOnly: true
