app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: docker.io/kpetrem/mqtt-exporter
            tag: latest
          env:
            TZ: "Europe/Vienna"
            MQTT_ADDRESS: 192.168.20.50
            MQTT_TOPIC: "tasmota/#"
            MQTT_V5_PROTOCOL: "true"
            PROMETHEUS_PORT: &port 3321
  service:
    main:
      ports:
        http:
          enabled: false
        metrics:
          enabled: true
          protocol: HTTP
          port: *port
      type: ClusterIP
      externalTrafficPolicy: Cluster
      ipFamilyPolicy: PreferDualStack
