---
apiVersion: v1
kind: Namespace
metadata:
  name: development
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: strimzi
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: kafka
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
