node-feature-discovery:

  installCRDs: true
  nodeFeatureRule:
    createCRD: true
  worker:
    config:
      core:
        sources: ["custom", "pci", "usb"]
      sources:
        usb:
          deviceClassWhitelist: ["02", "03", "0e", "ef", "fe", "ff"]
          deviceLabelFields: ["class", "vendor", "device"]
  prometheus:
    enable: true
