---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sonarr-secret
  namespace: media
spec:
  encryptedData:
    SONARR__API_KEY: AgCqvltHYuPIrObL131SFRoqwwTY4wGLcdVhj9QDzflP6a/eToYq2/gJRrjJ+kUkwezOlSFDxsSIgB7spt06vNDuaAWpfTk4QqnVFQJfXI2vTLbFaBra/3hoZir65UVkJNj/maS8LhwIlvB0QqCQIIbLnILZwuofEK8rKa5IFmdZMRRFrFPCYCt72iUzLrIbnZhYkQrrqF692Iczg7zkkLti1OUuCNXwnBHiig5Yq52RDpSY/cIwRVgu3xnF3i3YqK7UXPWaO4AdaWHlPfQ4QEYhCXoAPxcSMyla+xjwP2yMl3gCbs5A4brV/BgbPxWnF+0C5s0a7hhz/Q32JMr/Y9t3Rb6TPODMexUpcwxZykF7hb3R9tojQqBr4SWE80/peen4GzGNiTas3OWkh6zSw6Ir5zBp7AFcpcrzLwfpKPLeQ3G1gYhxJ8cpGtUscgL89EgTNIiQ2Z5AntTbE5wt5Qxo6I0jL0oR8vWTbzKalQTcyf1kIJNOwMemM0uf+5f0VVAtwKTicfDCy6bd6iFeeKKMUvRkwGQeT0nKhLNxtzq/yIb7GkkUOXIa6jBfnqBKrtQYNo21/n+v0Yy3c3RTT/x51shtSnDqhgFzpdrbEYanSmqwhbns6x8uDck6NR96bCG4jbc/cSbnxGyqbmBXWNzzhoiRqwxLA88dovh3Kit0eYdmtfGA+Qotyjm2V6hs0psvWHB+Xfkm+6GgnbNh5tsTW6PVvGJhZs5aQadN58nMuA==
  template:
    metadata:
      creationTimestamp: null
      name: sonarr-secret
      namespace: media
    type: Opaque
