longhorn:
  persistence:
    defaultClassReplicaCount: 2
  defaultSettings:
    defaultReplicaCount: 2
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      hajimari.io/icon: game-icons:bull-horns
      cert-manager.io/cluster-issuer: letsencrypt
    host: longhorn.ismailbay.dev
    tls: true
    tlsSecret: longhorn-tls
