longhorn:
  persistence:
    defaultClassReplicaCount: 2
  defaultSettings:
    defaultReplicaCount: 2
    backupTarget: s3://k8s-dev-stack-velero@minio/longhorn
    backupTargetCredentialSecret: longhorn-minio-credentials
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      hajimari.io/appName: Longhorn
      hajimari.io/icon: game-icons:bull-horns
      cert-manager.io/cluster-issuer: letsencrypt
    host: longhorn.ismailbay.dev
    tls: true
    tlsSecret: longhorn-tls
