---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app strimzi
  namespace: flux-system
spec:
  dependsOn:
    - name: longhorn
  targetNamespace: development
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/development/kafka/strimzi
  prune: false
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: strimzi
      namespace: development
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
