---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app strimzi
  namespace: flux-system
spec:
  targetNamespace: strimzi
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/development/kafka/strimzi
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: strimzi
      namespace: strimzi
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app kafka
  namespace: flux-system
spec:
  dependsOn:
    - name: strimzi
  targetNamespace: kafka
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/development/kafka/kafka
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: kafka.strimzi.io/v1beta2
      kind: Kafka
      name: kafka-at-home
      namespace: kafka
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app redpanda-console
  namespace: flux-system
spec:
  interval: 1h
  path: ./kubernetes/apps/development/kafka/redpanda-console/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
