app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/onedr0p/sonarr-develop
            tag: 4.0.0.737@sha256:b87e975273270c62adff5df680d8d2159c0a9fe49466aabee30546685efd0ac8
          env:
            TZ: Europe/Vienna
            SONARR__PORT: &port 80
            SONARR__INSTANCE_NAME: Sonarr
            SONARR__LOG_LEVEL: warn
            SONARR__AUTHENTICATION_REQUIRED: DisabledForLocalAddresses
          envFrom:
            - secretRef:
                name: sonarr-secret
          probes:
            liveness: &probes
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /ping
                  port: *port
                initialDelaySeconds: 0
                periodSeconds: 10
                timeoutSeconds: 1
                failureThreshold: 3
            readiness: *probes
            startup:
              enabled: false
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 1Gi
      pod:
        securityContext:
          runAsUser: 568
          runAsGroup: 568
          runAsNonRoot: true
          fsGroup: 568
          fsGroupChangePolicy: OnRootMismatch
          supplementalGroups: [10000]
  service:
    main:
      ports:
        http:
          port: *port
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        hajimari.io/icon: mdi:movie-roll
      hosts:
        - host: &host sonarr.ismailbay.dev
          paths:
            - path: /
              service:
                name: main
                port: http
      tls:
        - hosts:
            - *host
          secretName: sonarr-tls
  persistence:
    config:
      enabled: true
      storageClass: longhorn
      existingClaim: sonarr-config
      retain: true
      advancedMounts:
        main:
          main:
            - path: /config
    tv:
      enabled: true
      type: nfs
      server: 192.168.20.50
      path: /mnt/tank/media
      globalMounts:
        - path: /tv
          subPath: tv
    downloads:
      enabled: true
      type: nfs
      server: 192.168.20.50
      path: /mnt/tank/garbage
      globalMounts:
        - path: /downloads
          subPath: tv
