apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:bt2zyP2iB2brpreQag==,iv:erRUYE0p0JfvZfLJV4gMoRcQ8pl/fOZ2opFnMvO8Hao=,tag:QR2odojl0X5G5lBGwbtlig==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:ilMlSjcT5rKO1xPZskIZqJV0rw==,iv:IY//0f91meDaoZhueE9PUqVlC3RLKSVnonnbRrfq8kY=,tag:PLpl3MYOE2U/qJ6jdqXYRQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:BP/s4Toq92scmjcOcgUHxq7mfmFL8ZyliRPS9N7bQDDvbRXm,iv:3o/60jqwg2aC+teWZPbAY3MoBKEtnTe4z+MoJ9pzOG8=,tag:keDH9rZ+ywgjFzjWGIl2kg==,type:str]
    SECRET_RESTIC_REPOSITORY_TEMPLATE: ENC[AES256_GCM,data:FU9VXNi0yFJhLjlXH981fWj604suHQMn2haEXw/44wtIYz+auw==,iv:ZJw2q6wR2ygwxiYBTG5SDPNInNBF/JcvrA2IAo+aen0=,tag:1UxcF+HJhvPzPfNdrBFREw==,type:str]
    SECRET_RESTIC_ACCESS_KEY: ENC[AES256_GCM,data:V0tGsQf4xq5BNQ==,iv:GVmmR34zAta9cqJuHBbn26HdU7Ame/gsqhWlSmB5fvI=,tag:czYDId7huUex6XMbkiVQSg==,type:str]
    SECRET_RESTIC_SECRET_KEY: ENC[AES256_GCM,data:9II9+delLrT7RfnjcflwiOT/G3KO/mlP1nnK3EwX1P3SJqRdtiW7xA==,iv:99ks/O0cq+DiZEkzXRrs5Hxrot7B/9QzvFWtpvn9h5o=,tag:OR2X3pHSwZOjajLtmhDm2w==,type:str]
    SECRET_RESTIC_PASSWORD: ENC[AES256_GCM,data:LvcR/QVDI/sT0gLaWDPMpg==,iv:GcNcWZfiw3/wcaK+GGGO6oR3JJw0HdhbufGK2KxCIQ8=,tag:j4jgJf3E78Wk2tzZyOPAUg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rpz38k8uhgr5esalc2fr2jmced6m2c4j0puvs07wqm2u9ssg79ds3hlcam
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuR2xyWlhuU3A3VHBpVUY5
            SG5JdWJFWmx1LzRUMlZmd3dGdm1mQTdGUGlzCmZ3Zi8weFJoZURFL0dVZkpjSWlz
            c1JRZWlWamcvR0NTNStTanp5SjZMazQKLS0tIDZ6dHhxM2JQMVh6cUMwbSt1WkJj
            KzJBTUxYcEkyb3oyUHZQZlZYTFNJcVEKKgqsp18n0PL8DK6lOWsifqSliuMbzxIh
            V+bN0SDHOLC/x7+hFfT4IUg5vhyByRk6HWl6c25pr1aL6MrnUgiZCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-26T11:24:29Z"
    mac: ENC[AES256_GCM,data:wepatmPksWduUKd+P365OzlZsziNnBwmDU6hUmgIb56IybGXB2p+5b2OanVNo0+/vfeg8bviQiZzzwwEdoMo1m1zuIYewVwE9HhnBmygJF6FTP89VuaA0Y62yZX+CP1cUKsae4uz5kfBbbT7noSJwwVvgWVP0KSAWSxWjlXT23c=,iv:7CNJGNYA1yW16vRHlol6mpA71ZecPo+fy/aKFbJErTE=,tag:znHiFf+8dyOIwrD55vh0Qw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
