---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: test-topic
  labels:
    strimzi.io/cluster: ephemeral-cluster
spec:
  partitions: 1
  replicas: 3
  config:
    retention.ms: 7200000
