k8s-gateway:
  fullnameOverride: k8s-gateway
  domain: ismailbay.dev
  ttl: 1
  service:
    type: LoadBalancer
    port: 53
    annotations:
      io.cilium/lb-ipam-ips: "192.168.20.130"
    externalTrafficPolicy: Cluster
