apiVersion: v1
kind: Secret
metadata:
    name: longhorn-secret
stringData:
    AWS_ENDPOINTS: ENC[AES256_GCM,data:k1U+s3j89oSyPeTSQJwekxVGiltSW8MKlSs0nflHAC449k776PvTEYGjD0n6lXiPtTRfaZKMpPzQkXu4hO6BT+2qWaIDYKtRPnal+bN2KfiT,iv:A8VKceyiFwjIL3rdJPQ2suaadHQS/KPJOsGA2peuZd0=,tag:4iEoSNxxozr/RzKEQAYYig==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:oD1ELxfeLBDyhMq/8Bz+OvI3XN1vcKQUf/rydCCF2Xg=,iv:qK6w1GNwWzp0NQifOq/MIzJB54MygmV2bv9mxRvURX0=,tag:AI1ljFQJRRb6Lhc5zVv7lg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:YQkncWD/+TH/45iYr3qS5K6ON3yoi9ErPTV5sShl6VnDWbwoFoDjTfE99bSc5j1tDmISWmxx3jo03rvv75LViw==,iv:sjj9oEJAEGKsy8S8/k8vpqFdjpxFCZM4o2ZVks/mO2k=,tag:UCyS85mwgtttxpeZbD9rwg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rpz38k8uhgr5esalc2fr2jmced6m2c4j0puvs07wqm2u9ssg79ds3hlcam
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHUlAwWlpHZlkxdlNwUzZ2
            aGZPUGN2bWw3a2NVQk5qZCtIWW83aWtFV0RZCk9EakYzMmt6ZDdvUUI5eFJZTVky
            Y2UyNFJTTmcvSDMrWnJFdVQwZGREUG8KLS0tIEgxdW53eGZsR3dVcFhkS1dWY2VR
            cFlVQ21tTFQwbk5razlBdjVubzJieVUKaNR6nYl7U+dXBhTYcyIEj8kkUrX6pC7j
            eUNNxu7rkPbcu+IhPeal5fM8AINuixv63EI4bBPItk9Pnhx50Zm15Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-10T15:00:26Z"
    mac: ENC[AES256_GCM,data:+2e2WWPUQjllGdY/KfRAXMGbOzN4ubyi/tnG4rstF/2HJN8Ft7h+xUhqqp8KBoq0W0D++PUaFLSRoSRMK8wU1RHHzGTiFi1IPrGc3dA1mGHN+o3JhMrEmzBArtnf7QNqRBCKocBZDM1EqRXIVmV6HtGbT9tE4TAUWshb9GQoDik=,iv:DCWtJFKxviNUIJmP9QTj6L5SK1HHpdaKz04QJSdnofI=,tag:ulyorSOdJLZP4zx/rNyWKw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
