prometheus-node-exporter:
  fullnameOverride: node-exporter

  prometheus:
    monitor:
      enabled: true
      jobLabel: app.kubernetes.io/instance

      relabelings:
        - action: replace
          regex: (.*)
          replacement: $1
          sourceLabels:
            - __meta_kubernetes_pod_node_name
          targetLabel: kubernetes_node
        - action: replace
          regex: (.*)
          replacement: $1
          sourceLabels:
            - __meta_kubernetes_pod_node_name
          targetLabel: nodename
        - action: replace
          regex: (.*)
          replacement: $1.ismailbay.dev:9100
          sourceLabels:
            - kubernetes_node
          targetLabel: instance

  resources:
    requests:
      memory: 32Mi
    limits:
      memory: 64Mi

  hostNetwork: false
