---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  labels:
    app.kubernetes.io/name: homepage
data:
  bookmarks.yaml: |
    - Development:
        - Github:
            - href: https://github.com/ismailbay
              icon: github-light.png
        - Devhints:
            - href: https://devhints.io
              abbr: DH
        - CNCF:
            - href: https://cncf.io
              icon: si-cncf
        - kubesearch:
            - icon: kubernetes-dashboard.png
              href: https://kubesearch.dev
        - IT-Tools:
            - icon: it-tools-light.png
              href: https://it-tools.tech
        - Upstash:
            - icon: si-upstash
              href: https://console.upstash.com/kafka
        - Supabase:
            - icon: si-supabase
              href: https://supabase.com/dashboard/projects

    - Reading:
        - Daily.dev:
            - href: https://daily.dev
              icon: si-devdotto
        - Reddit:
            - href: https://reddit.com/r/homelab
              icon: reddit.png
        - Coding Horror:
            - href: https://blog.codinghorror.com
              abbr: CH
        - Kotlin Blog:
            - href: https://blog.jetbrains.com/kotlin/
              icon: kotlin.png
    - Other:
        - Youtube:
            - href: https://www.youtube.com/feed/subscriptions
              icon: youtube.png

  docker.yaml: ""
  kubernetes.yaml: |
    mode: cluster
  services.yaml: |
    - Infrastructure:
      - PiHole:
          icon: pi-hole.png
          href: http://192.168.1.2/admin
          widget:
            type: pihole
            url: http://192.168.1.2
            key: "{{HOMEPAGE_VAR_PIHOLE_API_TOKEN}}"
      - Proxmox:
          href: https://m720q-01.ibay.dev:8006
          icon: proxmox.png
          widget:
            type: proxmox
            url: https://m720q-01.ibay.dev:8006
            username: "{{HOMEPAGE_VAR_PROXMOX_API_TOKEN}}"
            password: "{{HOMEPAGE_VAR_PROXMOX_API_TOKEN_PASSWORD}}"
            fields: ["vms", "resources.cpu", "resources.mem"]
      - TrueNAS:
          href: https://truenas.ibay.dev
          icon: truenas.png
          widget:
            type: truenas
            url: https://truenas.ibay.dev:444
            key: "{{HOMEPAGE_VAR_TRUENAS_API_TOKEN}}"
      - Traefik TrueNAS:
          href: http://traefik.ibay.dev:9000/dashboard/#/
          widget:
            type: traefik
            url: http://traefik.ibay.dev:9000
      - Cloudflare:
          icon: cloudflare.png
          href: https://dash.cloudflare.com/
          widget:
            type: cloudflared
            accountid: "{{HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID}}"
            tunnelid: "{{HOMEPAGE_VAR_CLOUDFLARED_TUNNELID}}"
            key: "{{HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN}}"

    - Monitoring:
      - Grafana:
          icon: grafana.png
          href: https://grafana.ibay.dev
          widget:
            type: grafana
            url: http://grafana.observability
            username: "{{HOMEPAGE_VAR_GRAFANA_USERNAME}}"
            password: "{{HOMEPAGE_VAR_GRAFANA_PASSWORD}}"
      - Prometheus:
          icon: prometheus.png
          href: https://prometheus.ibay.dev
          widget:
            type: prometheus
            url: http://kube-prometheus-stack-prometheus.observability:9090
      - Cilium:
          icon: cilium.png
          href: https://hubble.ibay.dev

    - Selfhosted:
      - Flux:
          icon: flux-cd.png
          href: https://gitops.ibay.dev
      - Paperless:
          icon: paperless.png
          href: https://paperless.ibay.dev
          widget:
            type: paperlessngx
            url: https://paperless.ibay.dev
            key: "{{HOMEPAGE_VAR_PAPERLESS_API_TOKEN}}"
      - Gitea:
          icon: gitea.png
          href: https://git.ibay.dev
      - MinIO:
          icon: minio-light.png
          href: https://minio.ibay.dev
      - Home Assistant:
          icon: home-assistant.png
          href: https://hass.ibay.dev

    - Media:
      - Jellyfin:
          icon: jellyfin.png
          href: https://jellyfin.ibay.dev
          widget:
            type: jellyfin
            url: https://jellyfin.ibay.dev
            key: "{{HOMEPAGE_VAR_JELLYFIN_API_TOKEN}}"
            enableNowPlaying: true
      - Requests:
          icon: jellyseerr.png
          href: https://jellyseerr.ibay.dev
          widget:
            type: jellyseerr
            url: https://jellyseerr.ibay.dev
            key: "{{HOMEPAGE_VAR_JELLYSEERR_API_TOKEN}}"
      - Radarr:
          icon: radarr.png
          href: https://radarr.ibay.dev
          widget:
            type: radarr
            url: https://radarr.ibay.dev
            key: "{{HOMEPAGE_VAR_RADARR_API_TOKEN}}"
      - Sonarr:
          icon: sonarr.png
          href: https://sonarr.ibay.dev
          widget:
            type: sonarr
            url: https://sonarr.ibay.dev
            key: "{{HOMEPAGE_VAR_SONARR_API_TOKEN}}"
      - Downloads:
          icon: sabnzbd.png
          href: https://sabnzbd.ibay.dev
          widget:
            type: sabnzbd
            url: https://sabnzbd.ibay.dev
            key: "{{HOMEPAGE_VAR_SABNZBD_API_TOKEN}}"
      - Indexers:
          icon: prowlarr.png
          href: https://prowlarr.ibay.dev
          widget:
            type: prowlarr
            url: https://prowlarr.ibay.dev
            key: "{{HOMEPAGE_VAR_PROWLARR_API_TOKEN}}"

  settings.yaml: |
    title: Home Dashboard
    favicon: https://baydev.at/static/favicons/favicon-32x32.png
    theme: dark
    color: slate
    useEqualHeights: true
    headerStyle: clean
    hideErrors: true
    hideVersion: true
    target: _blank
    layout:
      Media:
        style: row
        columns: 4
    quicklaunch:
      searchDescription: true
      hideInternetSearch: true
      hideVisitURL: true
  widgets.yaml: |
    - datetime:
        text_size: xl
        format:
          timeStyle: short
          hourCycle: h23
    - openmeteo:
        latitude: "{{HOMEPAGE_VAR_OPENMETEO_LATITUDE}}"
        longitude: "{{HOMEPAGE_VAR_OPENMETEO_LONGITUDE}}"
        cache: 5
    - search:
        provider:
          - duckduckgo
