app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/onedr0p/radarr-develop
            tag: 4.7.5.7809@sha256:f2044d2e8bd2e8d24e8a79f051404be80400f450a94b4c481cbc93cfeffbe745
          env:
            TZ: Europe/Vienna
            RADARR__PORT: &port 7878
            RADARR__INSTANCE_NAME: Radarr
            RADARR__APPLICATION_URL: "https://radarr.ismailbay.dev"
            RADARR__LOG_LEVEL: warn
            RADARR__AUTHENTICATION_REQUIRED: DisabledForLocalAddresses
          envFrom:
            - secretRef:
                name: radarr-secret
          probes:
            liveness: &probes
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /ping
                  port: *port
                initialDelaySeconds: 0
                periodSeconds: 10
                timeoutSeconds: 1
                failureThreshold: 3
            readiness: *probes
            startup:
              enabled: false
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 1Gi
      pod:
        securityContext:
          runAsUser: 568
          runAsGroup: 568
          runAsNonRoot: true
          fsGroup: 568
          fsGroupChangePolicy: OnRootMismatch
          supplementalGroups:
            - 65539
  service:
    main:
      ports:
        http:
          port: *port
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        hajimari.io/group: Media
        hajimari.io/icon: mdi:movie-roll
      hosts:
        - host: &host radarr.ismailbay.dev
          paths:
            - path: /
              service:
                name: main
                port: http
      tls:
        - hosts:
            - *host
          secretName: radarr-tls
  persistence:
    config:
      enabled: true
      storageClass: longhorn
      existingClaim: radarr-config
      retain: true
      advancedMounts:
        main:
          main:
            - path: /config
    media:
      enabled: true
      type: nfs
      server: 192.168.20.50
      path: /mnt/tank/media
      globalMounts:
        - path: /media
