grafana:
  env:
    GF_DATE_FORMATS_USE_BROWSER_LOCALE: true
    GF_EXPLORE_ENABLED: true
    GF_FEATURE_TOGGLES_ENABLE: publicDashboards
    GF_SERVER_ROOT_URL: https://grafana.ismailbay.dev

  admin:
    existingSecret: grafana-admin-secret

  grafana.ini:
    analytics:
      check_for_updates: false
      check_for_plugin_updates: false
      reporting_enabled: false
    news:
      news_feed_enabled: false

  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: "default"
          orgId: 1
          folder: ""
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default
  datasources:
    datasources.yaml:
      apiVersion: 1
      deleteDatasources:
        # - {name: Alertmanager, orgId: 1}
        # - {name: Loki, orgId: 1}
        - {name: Prometheus, orgId: 1}
      datasources:
        - name: Prometheus
          type: prometheus
          access: proxy
          url: http://prometheus-operated.monitoring.svc.cluster.local:9090
          isDefault: true
      # - name: Loki
      #   type: loki
      #   access: proxy
      #   url: http://loki-gateway.monitoring.svc.cluster.local:80
      #   jsonData:
      #     maxLines: 1000

  dashboards:
    apps:
      cloudflared:
        gnetId: 17457
        datasource:
          - {name: DS_PROMETHEUS, value: Prometheus}
      external-dns:
        gnetId: 15038
        datasource: Prometheus
      node-exporter-full:
        gnetId: 1860
        datasource: Prometheus
      cert-manager:
        url: https://raw.githubusercontent.com/monitoring-mixins/website/master/assets/cert-manager/dashboards/cert-manager.json
        datasource: Prometheus
    storage:
      longhorn:
        gnetId: 16888
        datasource: Prometheus
    # infra:
    #   proxmox-ve:
    #     gnetId: 10347
    #     datasource:
    #       - {name: DS_PROMETHEUS, value: Prometheus}
    #   openwrt:
    #     gnetId: 11147
    #     datasource: Prometheus
    #   truenas:?
    kubernetes:
      kubernetes-api-server:
        gnetId: 15761
        datasource: Prometheus
      kubernetes-coredns:
        gnetId: 15762
        datasource: Prometheus
      kubernetes-global:
        gnetId: 15757
        datasource: Prometheus
      kubernetes-namespaces:
        gnetId: 15758
        datasource: Prometheus
      kubernetes-nodes:
        gnetId: 15759
        datasource: Prometheus
      kubernetes-pods:
        gNetId: 15760
        datasource: Prometheus
      kubernetes-volumes:
        gnetId: 11454
        datasource: Prometheus
    nginx:
      nginx:
        url: https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/grafana/dashboards/nginx.json
        datasource: Prometheus
      nginx-request-handling-performance:
        url: https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/grafana/dashboards/request-handling-performance.json
        datasource: Prometheus
    monitoring:
      prometheus:
        gnetId: 19105
        datasource: Prometheus
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      searchNamespace: ALL
      folderAnnotation: grafana_folder
      provider:
        disableDelete: true
        foldersFromFilesStructure: true
    datasources:
      enabled: true
      label: grafana_datasource
      searchNamespace: ALL
      reloadURL: "http://localhost:3000/api/admin/provisioning/datasources/reload"
    plugins:
      enabled: true
      label: grafana_plugin
      searchNamespace: ALL
      reloadURL: "http://localhost:3000/api/admin/provisioning/plugins/reload"

  plugins:
    - natel-discrete-panel
    - pr0ps-trackmap-panel
    - grafana-piechart-panel
    - vonage-status-panel
    - grafana-worldmap-panel
    - grafana-clock-panel

  serviceMonitor:
    enabled: true

  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      hajimari.io/appName: Grafana
      hajimari.io/icon: simple-icons:grafana
    hosts:
      - &host grafana.ismailbay.dev
    tls:
      - secretName: grafana-tls
        hosts:
          - *host

  persistence:
    enabled: false

  testFramework:
    enabled: false
