---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: networking
spec:
  encryptedData:
    api-token: AgByQXOL2O7mnFEJbiTB7KtVGs2tn1Ff6+4VT6ZZNp33AixVuVS0XBM1Jb83P3EUhOiaYEpcvCfT+mvBfUF9AYmXzSQvFhKbWSyCdR6gnEi5iyRgIYn8TEqHRt0aZmtwv6StPIiQOgkEmRVGjjkmnyCbFAcc4gZ/FLG0/4aohe7YgFNGE9qvSgfSdF1t0qo/G1v3vV6zM4sGEpM6Hy57VRBNk3e5XGcPHYFzYz8x1g9VhzwKy6f9Hsv3HutVeKUoN5Ogk7i66xscnT8z5/4vL/1Nnq7OX9jBSvs9pcVg1KiWnOc5n7NkDdK+YTn9/53ylIdG90+jjfpsVw+DIPNEFDfnV4ubGEi1XYuzCe8HT97Z7LmYOxWFS01iWbHfxvObWmS2bloWnBrXGPzc+uayB2GNqHfyqHcwPaNyaDUUKlnRCGMdiz+Jl5grRAneiw4Abvrksn5Lq2CPntUOFQuqeEwF8FARdTrpsSLE5W6ZeCP3AqOae59+kNX4b9gkWk6ystjwgcbNd6uXFfRTTBrulEQ+3KP2cGwLIfwfO0IdvNWC4U9HCI7aQ6Y38WS5GDeTYKCEDvZEGBHLFXnIlm/1ZNS4mcSe4MsyeJOvhbLGougw1g3XdYxNtqVC5qLaijiwu8RdkoQ5FdIx1WmC4ICBQ2MWUtSCBT5IkA09rIiM/Y0dciVl87rZPUQZzWg4koyydio6kqVWLd/f7fIK0vJl6LmivfYN+ktq4RFXqeSe7E/8Ez3L3v5E1rof
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: networking
    type: Opaque
