---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: networking
spec:
  encryptedData:
    api-token: AgCZM8dIl7xvtwABbjB7TA5ltWQj4icFZtbvWodztukmi7PYCulpJuLcmSqC9Ha2IwECmnwF0F0mrWi2lJ7aS+nMdBXUHmPQ8VafA6gRfenkGSeey6p1wB7wUXyounAsxF7kNvq3fHnDIhOnWrv7XRatvpuCyYgGjL5BUFu3uzc1s6cF3Pi18wxvPeufVx3YwFC44Ho4LjmZvlda3F9GCoYNho8+AVvEagkbvh4f/T3g8v1P70VJiqrz4esivFijKStE6ZjiPoxjyOCtTLlBgjFGhw6OLsdXzBDfuMgR5Hhn5yeKFw3n/deydZVGHHG6kaSLBlYLirZTi0S7FjkFY7VOB5MuHmzTSgZZnHCl4FbNQEq1ejgYVUGSnjA7HOJhD57HOGqT9BnoYR0x4jQ4vOhsbSvGD3a2Q9dxtvxTMK4Av3l9BvZH9u/3HDKr9ZEUXWtn0KB1VMi+kSF3zSGmFtN6U3QdL2TsUvIIZgwbathG4xopZgwNXFPdMTBnBbd/hKoiQszSotW3ru03C49DmOr+47SucUA6RNf028w982h//eaXOU976246wG9iiAgm7AsqPSjyHWpx0GtAMgYlZsOcgEl9UabGSFY2SWgRfzduK2STntvieVbYBmbAnYmfszKpq1ifFK6x7rmL501fZyOd1gKUgSihN4zQQso8fovQXYGSoElHLEa6pGq5u1x50pfI4dRTNmGFiv6yeDkkrC02WU2pOpKwKWy65cb/+5aW4hGLx5YiXzYc
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: networking
    type: Opaque
