---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: networking
spec:
  encryptedData:
    api-token: AgCuu9a+9gvYGL3/B3BEK64VZ1ILRwViFEF7R4Ax5wrUc/CagWA8xPPF1Hiu3PtdM1HSoFV3EpyCVXqyLdMxKWXWFmmwj5ytbPctwqGtG2H65npEGdZp1XZRtoAVZ/uaUedQiu0SbkSrr1LirY5CXwtUshjxTu9WRutYnezTSmRjzdknXHMOTn0k8q18IJxqXG9B628qcUxVaDhBdEC/WyxgW6080+GOMqxruXf+VOHTgxrFqABRCLt4ojyTB7C/BR1jXT0p9xYrw8T6a1/PDymi1mw+wZJotQdPX8s9NSTQ3u2pkP71akgiUNRUZhuEmZIF6lNK1fDoatdKEMyC2CNsvkzWHM5QubrpE6pEu7BTtfYKTdl7gc+LOcBTAKEi+48CWbWi2QgjQr15KX1nWjhUrHJs8DqfrY+UwP0oJiPFFudbnZtZWaDFSTxKAHOyCE0uLK5qbElK0msouqLJ84e/0Y7YD/PxnRbwP6YGG9x6P9G5hqv/6UoIK4uxFaoM+OZDeRcIf8QYewvufxPxt4iuUK/Vn/edKAa6Rn9YFjOt5kDeuSII5Q+MYc76luMT3Z+nPx7Y4JEENQu3cmNv9PyuGy/o9togIe93MEn33FJz5aWA85kKsV7QCAFXjHyFPVu6YiUKQhCWq+/bluoSNK7rMg8EU8pQ7yUKhRXchEpSHEwlnXcM27+U2thLEqW5M36mia6wX3qo1zVArwzLkuSwQosKPRg/bPpAGvOvV7MxEfnOQTP/sozI
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: networking
    type: Opaque
