---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: networking
spec:
  encryptedData:
    api-token: AgBfGz2Nh5XdR2pilZ9qgtSS28qRyMKJY4pO39iZK7RgyaDjL5f3I45kcbrDeB2639YbMstLh8zRJbFKTvl+11BgJlopqBSOd3Zu901Wtf6kL9SEucwbhEsfMcdfZKjhmBYWRQqTaxV/csyWgbfhELFvTmL4fHGMHxfJ4b2tQc0czh7euNDLv6m0r62t2b4gMpRwf0FBfBCz+AHZPqoKwISlMLXUD3Qo9i4qgzC51eR/UwVQW4foxUg1jeloxrGhM3Pl3AoCqYP72k09AwmNRbCNlGZYWAESb+GZRzCwilCrFQ7ecvAIiBEpb4s3p7VMm1D38gMoRsHT5+/yI2tEqdFG3BM49pQ8cIijaiJ36zNYNA9clmtteHGDA9tBeMcDT+gMMhAxxlPqj2A2tJHifEXx3/Vymc4GjA6uDUQadCZywNr85y2xe4gcpxo2nXqvSBKUxnZ4Z2mvKk3NF2FpTkQ5jOBP5bmQItF6OL4mrT9Er+XRXnE71/tHS5CArpjvkbcZyVMnyqQuB0ErAvUjFiJx3qTe8vrOEHZcDnFKRTARYZqZ+g3lIVJrP9qENSOZC9nI8buuDxt1Myjew+7fzOZnXSLZgZQuKBjxxTjs2BwJWMJUpZqlOe+5cKtAZ7hsSrMOupPbb/UQ/L2Juj9BnS18gVKa6cZ/UOiLB8+WwVhQ9Ej0HD1lEzydXhkTUoOA/YacVdNhH7PoQffJGm90Y9KwFcQs/2ZDxwqhTsp4UQiEztrXJOlXjVqD
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: networking
    type: Opaque
