app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: docker.io/fallenbagel/jellyseerr
            tag: 1.7.0
          env:
            TZ: Europe/Vienna
            LOG_LEVEL: warn
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 1Gi
      pod:
        securityContext:
          runAsUser: 568
          runAsGroup: 568
          runAsNonRoot: true
          fsGroup: 568
          fsGroupChangePolicy: OnRootMismatch
  service:
    main:
      ports:
        http:
          port: 5055
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        hajimari.io/group: Media
        hajimari.io/icon: mdi:jellyfish
      hosts:
        - host: &host jellyseerr.ismailbay.dev
          paths:
            - path: /
              service:
                name: main
                port: http
      tls:
        - hosts:
            - *host
          secretName: jellyseerr-tls
  persistence:
    config:
      enabled: true
      storageClass: longhorn
      existingClaim: jellyseerr-config
      retain: true
      globalMounts:
        - path: /app/config
