---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBmek3o03ICfUTZwuU19X1lyFYljqHvdr3v58Ve4/H8d+k1jOtvwR0fP9Fh9Eify7sRt4XpDu3hzrtza00wVqX8DjIP+A0aUydx5t1/K3+QQHoOlAN9g4kZ01mstIQE6J0v9SNCYcghUZKs83L6MhRF4J8xozcscd3Jv8pP/zQ8jdtuJ7D/1PkV9BsFQ0YTVTiKMdzgflr1uHrxh4W/9c/JHiMqx68Z4Qaa8vF37fVxVaWrIeDLpLKTJ97XE9cPjKJXSvD55BvQuFtMTtT9ZrjimWJHeKfLM5lfz1rC3gy5OAv/Ym4cyzoEwnAsIEhkh7Sv9zw8NaC8hlOMB2DX4drFxuZs2Z1OInhDr4GfQV3ySWeRq/yrx7khhoLUlA/7qpsPwTCs6yqR2s8It1LWpCZYVtVrXstV4nNsWnJnNTUdquJ1C9P9nfR0IuLTN4lY0W6t8QCMiFcQDvshVCraMDQLs0cNp79ps7KMw6b55peiGkeFyRgTB3boUtXZIqujsGrvaMdArRAKHsE62y9tCxxskQrdttXBqzmlwO64foK3hmukbGuYp51weiI3KrRfTi/YsWBp0udW/tlybzi1I3wOCkrPNbCluWep5D6dzvsrZd4QUoNSogogVRaqUD2owzkBTuaNW7z0v6cuaYiQ/KQ5DesbUKAAYXQeFA/I3821tqTLMIdKRAjcQoYCQow/87R6DWo1cHlqxZI0lV3aSnUWXbaePf7O1fW6pURN6gk98dnMZr/oO2KA
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
