---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: network
spec:
  encryptedData:
    api-token: AgBZVcVBZ8E9rsFORnqiCd8QMEmbWCJ22iypQWYDHBDq/sMG9bMKrjq0W93oZU2gg5w/h+tpJLdyZGWuzk524Y7c18gbEw+9tGiACERlNkQhqB7m27rUT8gNgRkCmKG3Wgz7JTgv5HGRjnly6mpuy/oMxYJ9E8oE/RFM5Xt0cm0904Ouaz0wTiPpITnOM9kj9TA3Wu4iDdZCFFO0KfNziHSGs2LpYlJPbEXRElTzOVgwodblCj2UjbLaohaS4VbBA7E9yhZk6FQPDRwlyDZRoErjWt/mgN3HCR1biebj7MyMv6IjqGFD4ZqXsT/p/ZuEwjDInTQoS/kRiUV5//cQe59L/Kr9Npge9FMlb7H+H2KzcEGpOvXxSHIfDRasw4T7YDtd1dnWtAYRTgklrIKrKecmtuHE7iSDHW69tjO/00LJc6qhciTfTlyiT472sXSsgo6Mt0cI4cvEuitX05LATC1UPCMMec7XmvOz6wWXCMiZWdrei24+IW4ydOiYJPbCGme2ZDAWDOrNLLJP4m/4/CRi4VosZo/LJ0h8ZXxJ5MoTP/UBffax9wHlTQtGxn8DwtMfT+kJTLifRyEDw35+r9aFtYY54eKBO01Ggz4AF/q8bY0dzWMGFaU2Ywm2BthjZ+hdOdNS5sXNbJr6CUfnV1awAAcomnRKPJCbJ9FoekJcfbnqcvODIJuaFF7Cwivmomu2O05Dfe7pRg+RLYkW4WKrEolvGkmeRr/QH553ql4zPR6Rz8kUeLjK
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: network
    type: Opaque
