app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/onedr0p/prowlarr-develop
            tag: 1.11.1.4146@sha256:c7ad70aaf1dae541ec0fdae0a449cbfcab1e2dd31c46e92f758b4006bfef4a53
          env:
            TZ: Europe/Vienna
            PROWLARR__PORT: &port 9696
            PROWLARR__INSTANCE_NAME: Prowlarr
            PROWLARR__LOG_LEVEL: warn
            PROWLARR__ANALYTICS_ENABLED: "False"
            PROWLARR__AUTHENTICATION_REQUIRED: DisabledForLocalAddresses
          envFrom:
            - secretRef:
                name: prowlarr-secret
          probes:
            liveness: &probes
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /ping
                  port: *port
                initialDelaySeconds: 0
                periodSeconds: 10
                timeoutSeconds: 1
                failureThreshold: 3
            readiness: *probes
            startup:
              enabled: false
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 1Gi
      pod:
        securityContext:
          runAsUser: 568
          runAsGroup: 568
          runAsNonRoot: true
          fsGroup: 568
          fsGroupChangePolicy: OnRootMismatch
          supplementalGroups:
            - 65539
  service:
    main:
      ports:
        http:
          port: *port
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        hajimari.io/icon: mdi:movie-roll
      hosts:
        - host: &host prowlarr.ismailbay.dev
          paths:
            - path: /
              service:
                name: main
                port: http
      tls:
        - hosts:
            - *host
          secretName: prowlarr-tls
  persistence:
    config:
      enabled: true
      storageClass: longhorn
      existingClaim: prowlarr-config
      retain: true
      advancedMounts:
        main:
          main:
            - path: /config
    media:
      enabled: true
      type: nfs
      server: 192.168.20.50
      path: /mnt/tank/media
      globalMounts:
        - path: /media
