kube-prometheus-stack:
  crds:
    enabled: true
  cleanPrometheusOperatorObjectNames: true

  alertmanager:
    enabled: false # TODO: activate and configure this!

  grafana:
    enabled: false

  kubelet:
    enabled: true
    serviceMonitor:
      metricRelabelings:
        # Remove duplicate labels provided by k3s
        - sourceLabels: ["__name__"]
          regex: "(apiserver_audit|apiserver_client|apiserver_delegated|apiserver_envelope|apiserver_storage|apiserver_webhooks|authentication_token|cadvisor_version|container_blkio|container_cpu|container_fs|container_last|container_memory|container_network|container_oom|container_processes|container|csi_operations|disabled_metric|get_token|go|hidden_metric|kubelet_certificate|kubelet_cgroup|kubelet_container|kubelet_containers|kubelet_cpu|kubelet_device|kubelet_graceful|kubelet_http|kubelet_lifecycle|kubelet_managed|kubelet_node|kubelet_pleg|kubelet_pod|kubelet_run|kubelet_running|kubelet_runtime|kubelet_server|kubelet_started|kubelet_volume|kubernetes_build|kubernetes_feature|machine_cpu|machine_memory|machine_nvm|machine_scrape|node_namespace|plugin_manager|prober_probe|process_cpu|process_max|process_open|process_resident|process_start|process_virtual|registered_metric|rest_client|scrape_duration|scrape_samples|scrape_series|storage_operation|volume_manager|volume_operation|workqueue)_(.+)"
          action: keep
        - sourceLabels: ["node"]
          targetLabel: instance
          action: replace
        # Drop high cardinality labels
        - action: labeldrop
          regex: (uid)
        - action: labeldrop
          regex: (id|name)
        - action: drop
          sourceLabels: ["__name__"]
          regex: (rest_client_request_duration_seconds_bucket|rest_client_request_duration_seconds_sum|rest_client_request_duration_seconds_count)

  kubeApiServer:
    enabled: true
    serviceMonitor:
      metricRelabelings:
        # Remove duplicate labels provided by k3s
        - sourceLabels: ["__name__"]
          regex: "(aggregator_openapi|aggregator_unavailable|apiextensions_openapi|apiserver_admission|apiserver_audit|apiserver_cache|apiserver_cel|apiserver_client|apiserver_crd|apiserver_current|apiserver_envelope|apiserver_flowcontrol|apiserver_init|apiserver_kube|apiserver_longrunning|apiserver_request|apiserver_requested|apiserver_response|apiserver_selfrequest|apiserver_storage|apiserver_terminated|apiserver_tls|apiserver_watch|apiserver_webhooks|authenticated_user|authentication|disabled_metric|etcd_bookmark|etcd_lease|etcd_request|field_validation|get_token|go|grpc_client|hidden_metric|kube_apiserver|kubernetes_build|kubernetes_feature|node_authorizer|pod_security|process_cpu|process_max|process_open|process_resident|process_start|process_virtual|registered_metric|rest_client|scrape_duration|scrape_samples|scrape_series|serviceaccount_legacy|serviceaccount_stale|serviceaccount_valid|watch_cache|workqueue)_(.+)"
          action: keep
        # Drop high cardinality labels
        - action: drop
          sourceLabels: ["__name__"]
          regex: (apiserver|etcd|rest_client)_request(|_sli|_slo)_duration_seconds_bucket
        - action: drop
          sourceLabels: ["__name__"]
          regex: (apiserver_response_sizes_bucket|apiserver_watch_events_sizes_bucket)

  kubeControllerManager:
    enabled: true
    endpoints: &node_ips
      - 192.168.10.110
      - 192.168.10.111
      - 192.168.10.112

  kubeScheduler:
    enabled: true
    endpoints: *node_ips
    serviceMonitor:
      metricRelabelings:
        # Remove duplicate labels provided by k3s
        - action: keep
          sourceLabels: ["__name__"]
          regex: "(apiserver_audit|apiserver_client|apiserver_delegated|apiserver_envelope|apiserver_storage|apiserver_webhooks|authenticated_user|authentication|disabled_metric|go|hidden_metric|kubernetes_build|kubernetes_feature|leader_election|process_cpu|process_max|process_open|process_resident|process_start|process_virtual|registered_metric|rest_client|scheduler|scrape_duration|scrape_samples|scrape_series|workqueue)_(.+)"

  kubeProxy:
    enabled: false

  kubeEtcd:
    enabled: true
    endpoints: *node_ips

  kubeStateMetrics:
    enabled: false

  nodeExporter:
    enabled: false

  prometheus:
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        hajimari.io/appName: Prometheus
        hajimari.io/icon: simple-icons:prometheus
      hosts:
        - &host prometheus.ismailbay.dev
      tls:
        - secretName: prometheus-tls
          hosts:
            - *host
    thanosService:
      enabled: true
    thanosServiceMonitor:
      enabled: true
    prometheusSpec:
      replicas: 1
      replicaExternalLabelName: __replica__
      ruleSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false
      probeSelectorNilUsesHelmValues: false
      scrapeConfigSelectorNilUsesHelmValues: false
      enableAdminAPI: true
      walCompression: true
      retention: 2d
      retentionSize: 15GB
      enableFeatures:
        - auto-gomaxprocs
        - memory-snapshot-on-shutdown
        - new-service-discovery-manager
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: local-path
            resources:
              requests:
                storage: 20Gi
      thanos:
        image: quay.io/thanos/thanos:v0.32.5
        objectStorageConfig:
          existingSecret:
            name: thanos-objstore-secret
            key: objstore.yml
      resources:
        requests:
          cpu: 150m
          memory: 1Gi
        limits:
          memory: 2Gi
