app-template:
  controllers:
    main:
      annotations:
        reloader.stakater.com/auto: "true"

      pod:
        annotations:
          io.cilium/lb-ipam-ips: "192.168.20.130"

      containers:
        main:
          image:
            repository: ghcr.io/home-assistant/home-assistant
            tag: 2023.12.3
          env:
            SECRET_RECORDER_DB_URL:
              valueFrom:
                secretKeyRef:
                  name: home-assistant-pguser-home-assistant-pguser
                  key: uri
          envFrom:
            - secretRef:
                name: home-assistant-secret
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false

  service:
    main:
      ports:
        http:
          port: 8123

  ingress:
    main:
      enabled: true
      className: nginx
      hosts:
        - host: &host hass.ismailbay.dev
          paths:
            - path: /
              service:
                name: main
                port: http
      tls:
        - hosts:
            - *host

  persistence:
    config:
      enabled: true
      accessMode: ReadWriteOnce
      storageClass: longhorn
      size: 1Gi
      advancedMounts:
        main:
          main:
            - path: /config
