---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: operator-lifecycle-manager
spec:
  interval: 30m
  chart:
    spec:
      chart: olm
      version: 0.30.0
      sourceRef:
        kind: HelmRepository
        name: cloudtooling
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    namespace: olm
    catalog_namespace: olm
    